//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonVehicle
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UploadedFile
    {
        public int IDUploadedFile { get; set; }
                 
        [Required]
        [MaxLength(20)]
        public string Name { get; set; }

        [Required]
        [MaxLength(20)]
        public string ContentType { get; set; }

        [Required]
        public byte[] Content { get; set; }
        public int VehicleIDVehicle { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
    }
}
